### ISSUE TITLE
Markdown processor issue - Single-quotes in tag attributes.

### ISSUE THREAD

**Issue by andreas-kupries** [tclssg/tclssg#46] opened 2015-01-23 23:43 UTC
The following test page where I used HTML in MD to get a nice table causes the markdown processor to drop the second table from the output! This was clearly seen with the dump feature where the 2nd table is in the input to markdown, and not in the HTML.

    {
        title {Testing stuff}
        hideSidebarNote 1
    }

    <table><tr>
    <td>Array</td>
    <td><a href='http://core.tcl.tk/akupries/array'>Core</a></td>
    </tr></table>

    <table><tr>
    <td>Tcl</td>
    <td><a href='http://core.tcl.tk/tcl'>Core</a></td>
    </tr></table>

I have found two ways of fixing this in the input:
(1) Remove the column contain the <a> reference.
(2) Change the single-quotes around the href-url to double-quotes.

It seems that the markdown processor chokes in some way on the single-quotes.
As AFAIK HTML allows either single- or double-quotes around attribute values and markdown allows arbitrary HTML this looks to me a bug in the markdown processor in question.

Which is the internal one, looks like.

I suspect that this issue has to be handed to the Caius project for actual fixing.

... Or not. Looks to be line 325 in your copy of markdown.tcl
Replacing it with

    set re_htmltag {<(/?)(\w+)(?:\s+\w+=(?:\"[^\"]+\"|'[^']+'))*\s*>}

and the problem is fixed. The new regex is based on the variation I found in line 431 (proc parse_inline) of the same file.

Should still be forwarded to upstream Caius.

As a side note it seems that Caius does not handle the extended syntax github supports for tables. I.e. I  took the tclssg Readme.md, put it into my test site and processed it. The tables are not coming not out as tables but a wall of text. That could be a feature request for Caius.

**Comment by dbohdan** [comment] 2015-01-24 14:13
>As AFAIK HTML allows either single- or double-quotes around attribute values and markdown allows arbitrary HTML this looks to me a bug in the markdown processor in question.

I've checked and [they are](http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2). Other Markdown processors I've tried handle this just fine as well. 

>it seems that Caius does not handle the extended syntax github supports for tables

Yep. Those are [nonstandard](https://help.github.com/articles/github-flavored-markdown/) if you take the original Markdown.pl to be the standard and apparently [CommonMark](http://spec.commonmark.org/0.16/) hasn't yet specced them, either. It's your call whether to request this feature now but I'd consider it a reasonable request. Tables and GitHub's implementation of them are likely to match the future spec/test suite produced through the coordination by some of the biggest Markdown users.

While I do have a local copy of `markdown.tcl` to keep Tclssg self-contained the code is taken verbatim from upstream. The bug is also reproducible outside of Tclssg, so this is definitely an upstream issue. I could fix it locally using your patch but I'd rather keep in sync with the Caius Project, esp. since they have a test suite for Markdown to ensure changes don't break anything (not that I expect yours to). Could you file a bug report at https://github.com/tobijk/caius/issues?

**Comment by andreas-kupries** [comment] 2015-01-24 21:54
Done.
  - [Quoting bug](https://github.com/tobijk/caius/issues/16)
  - [Table support](https://github.com/tobijk/caius/issues/17)

**Comment by tobijk** [comment] 2015-02-10 20:15
Thanks a lot for your interest and contributions to Caius' Markdown module. I implemented the table syntax. Let me know if you encounter any problems.

**Comment by dbohdan** [comment] 2015-02-11 13:45
Thanks, @tobijk! I'm closing the issue.

**Closed by dbohdan** 2015-02-11 13:45 UTC
Labels: bug, upstream
